orbitable/engine

src/body.js
src/engine.js
src/engine_debug.html
src/engine_debug.js
src/vector.js
test/body.js
test/vector.js

Cleaned up simulator more, removed code exclusively relevant to legacy
design. Expanded body class from other branch.
First time running into issue of "require" not being usable when running javascript through client, looking for solution.

Closer to functionality, preparation for integration.

---

src/body.js
src/engine.js
src/engine_debug.html
src/engine_debug.js
src/vector.js

engine_debug shows how the simulator can be run

Simulator is running

---

src/body.js
src/engine.js

Destroying a body sets its exists flag to false and radius to 0.

'Destroying' body also sets its physical attributes to 0

---

package.json

Problem
=======
There is no tagged versions for consumers to pin to.
Solution
========
Howto Test
==========

Release Initial Version of Engine; Closes #17

---

.travis.yml
test/vector.js

Problem
=======
The tests for engine are not automatically run.
Solution
========
Add continuous integration with Travis CI. Travis will watch the repository and run the tests for every push. It then reports the success of the tests in a multitude of ways. This lets the team know when a new change introduces regressions or issues.
Howto Test
==========
[travis_engine]: https://travis-ci.org/orbitable/engine/settings

Add Continuous Integration; Closes #19

---

package.json

The API now includes the reset function. We should prepare a release for use in bridge.

Prepare 0.0.2 Release; Closes #23

---

src/engine.js

The numbers will exceed javaScript’s safe integer bounds but the
precision is still adequate for our needs. Down-scaling needs to be done in bridge to compensate for the large scale of the simulation.

Engine now uses unscaled units

---

package.json

The first stable release of the engine!
Change Log
==========
Issue #28: Use Correct Parameters When Parsing

Prepare 0.1.0 Release; Closes #30

---

src/body.js
src/engine.js
test/engine.js

Bodies can now be identified by simulator-unique IDs, new functions for
adding and deleting bodies.

Add/delete bodies from simulation, Bodies have unique IDs

---

package.json

Release 0.1.2 adds the ability to add and remove bodies to/from the simulation

Release 0.1.2

---

src/body.js
src/engine.js
test/body.js
test/engine.js
test/vector.js

Body and Vector currently have all functions covered, engine still
needs tests on update function.

Unit tests for body, vector, and engine

---

src/engine.js
test/engine.js

Slammed out most of the tests for engine.

Issue#39/clean update

---

src/body.js
src/engine.js
test/body.js
test/engine.js

Issue#39/mission codename complete coverage; Closes #9; Closes #39

---

LICENSE
package.json
src/body.js
src/engine.js
src/vector.js
test/body.js
test/engine.js
test/vector.js

Problem
=======
The library is unlicensed.
Solution
========
Add a license.
Howto Test
==========

Add License; Closes #5

---

src/body.js
src/planetNamer.js
test/body.js
test/planetNamer.js

Adds body name attribute as well as a generator to create a name if none is given in the constructor.

Add body names; Closes #46

---

src/body.js
test/body.js

Body attributes can be updated in any combination via body.update(body)
function.

Update body attributes via update function; Closes #44

---

src/engine.js
test/engine.js

New function can receive a body ID and data object so the bridge can update body values without a direct reference to the body.

Update body with body ID via simulator; Closes #53

---

src/body.js
src/engine.js
src/orbit_tracker.js
src/vector.js
test/vector.js

Issue#36/tracker integration; Closes #36

---

src/engine.js
test/engine.js

Problem
-------
When the simulation is reset with a new set of bodies the simulation time
remains unchanged.
Solution
--------
Reset the simulation time when resetting.
References
----------
- Closes #72
- @aaroncameron21 Please review to make sure this makes semantic sense.

Reset Simulation Time with Reset

---

src/body.js
src/note.js

Deep copy functions to body and note

---

src/body.js

Also modified luminosity parsing
* Closes #80

Deep copy vectors in body.copy()

---

src/engine.js
src/note.js
test/engine.js

Reset clears everything, accepts notes

---

src/body.js
src/engine.js
test/body.js

Generate colors from random sampling

---

src/engine.js

This will allow bridge to auto-select a body or note when they are created by the user.
* Closes #85

Added return statements for addNote and addBody

---

src/body.js

Based on feeback from @benjic, I had to update the engine to add an extra param on updates. The only real change is on line 80, I am not sure how the formatting changes propagated. 
This will also need a new version tag, but I think that happens after the merge correct?

Add a hideHabitable parameter, neccesary for toggling habitable zones.

---

src/engine.js

____
* Closes #92 
* Closes #93

Set default note startTime, allow note editting after running

---

src/body.js
test/body.js

-Change it to the appropriate star color if the luminosity is greater than 0
-If luminosity is zero, change the color back to a regular body color
Fix an error I had made in the temperature calculation
Update Body color tests to reflect equation change

Update the color when the luminosity (or radius) changes

---

package.json
src/orbit_tracker.js
test/orbit_tracker.js

Tracker fix
